### ISSUE TITLE
Duplicating Buttons Issue

### ISSUE THREAD

**Issue by thenorthstar** [Raamyy/Haxball-Room-Search#6]
Hello @Raamyy @xenonsb. I have an issue about the amount of buttons in room.

So, I have a non-bot controlled room (that is, host player is me). Anyway, I have made my PC slept and gone out. And then turn on my PC again, and so, the room; and it I was given a re-captcha (in spite of not closing the room). So, I have passed it and then saw that the **HaxBall Room Search generated buttons** near the chat section were duplicated as on the image. Frankly I'm not sure how many people encountered with this issue but I can say that this issue is waiting for a solution. Thanks from right now!

![1](https://user-images.githubusercontent.com/68077608/119257748-48dd0200-bbcf-11eb-873c-f1e5c4123edd.png)

**Comment by Raamyy** [comment]
Hello @thenorthstar Do this issue persist with you, or it was just this incident?

**Comment by thenorthstar** [comment]
> Hello @thenorthstar Do this issue persist with you, or it was just this incident?

@Raamyy Dude it persists every time in which my PC was slept and then turned-on. That is, not this incident. Frankly I'm thinking that these buttons are re-triggered after every **room.onRoomLink** event (but not completely sure anyway). But interestingly, the other buttons (menu and settings) are not duplicated whereas these buttons are duplicated. In fact, I was going to write this issue on the original HaxBall wiki but I have noticed that just these buttons are duplicated so I have written this issue here.
